export const initCategory: IDynamicCategory = {
  createTimeSheet: {
    name: "createTimeSheet",
    label: "บันทึกข้อมูล",
    pageMode: "create",
  },
  editTimeSheet: {
    name: "editTimeSheet",
    label: "แก้ไขข้อมูล",
    pageMode: "edit",
  },
};

export const initForm: IDynamicFormModel[] = [
  {
    formCategory: "createTimeSheet",
    name: "workDate",
    type: "date",
    label: "วันที่ปฏิบัติงาน",
    value: "",
    readOnly: false,
    required: true,
    grid: 6,
  },
  {
    formCategory: "createTimeSheet",
    name: "workHours",
    type: "number",
    label: "เวลาการทำงาน",
    value: "",
    readOnly: false,
    required: true,
    grid: 6,
    numberMin: 1,
    numberMax: 12,
  },
  {
    formCategory: "createTimeSheet",
    name: "workDetail",
    type: "textarea",
    label: "รายละเอียด",
    value: "",
    readOnly: false,
    required: true,
    grid: 12,
  },
  {
    formCategory: "editTimeSheet",
    name: "workId",
    type: "text",
    label: "เลขที่เอกสาร",
    value: "",
    readOnly: true,
    required: true,
    grid: 12,
  },
  {
    formCategory: "editTimeSheet",
    name: "workDate",
    type: "date",
    label: "วันที่ปฏิบัติงาน",
    value: "",
    readOnly: false,
    required: true,
    grid: 6,
  },
  {
    formCategory: "editTimeSheet",
    name: "workHours",
    type: "number",
    label: "เวลาการทำงาน",
    value: "",
    readOnly: false,
    required: true,
    grid: 6,
    numberMin: 1,
    numberMax: 12,
  },
  {
    formCategory: "editTimeSheet",
    name: "workDetail",
    type: "textarea",
    label: "รายละเอียด",
    value: "",
    readOnly: false,
    required: true,
    grid: 12,
  },
];
